# Generated by Django 3.2.7 on 2022-12-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_auto_20221203_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='inventario')),
                ('price', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('medida', models.CharField(max_length=225)),
                ('expiration', models.DateField()),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.proveedor')),
            ],
        ),
    ]
