# Generated by Django 3.2.7 on 2022-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_totalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='totalPayment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
