# Generated by Django 3.2.7 on 2022-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
