# Generated by Django 3.2.7 on 2022-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
    ]
