# Generated by Django 3.2.7 on 2022-12-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='business',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='run',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
