# Generated by Django 3.2.7 on 2022-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PENDING1', 'pending1'), ('DELIVERED', 'delivered')], max_length=255),
        ),
    ]
