# Generated by Django 3.2.7 on 2022-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'delivered')], max_length=255),
        ),
    ]
